docs: Fix melos doc setup for windows (#2401)
Closes: https://github.com/flame-engine/flame/issues/2398

Finally got the script all figured out, so `melos doc-setup` works on
windows. It should work on Unix as well, but I can't verify. Its simply
scalar fold, color encoding removed, python string literal wrapped in
double quotes, and false converted to a bash exit.

diff --git a/melos.yaml b/melos.yaml
--- a/melos.yaml
+++ b/melos.yaml
@@ -47,16 +47,16 @@ scripts:
     description: Run dartdoc checks for all packages.
 
   doc-setup:
-    run: |
-      echo '\033[1;32mChecking python version:\033[m' &&
+    run: >
+      echo 'Checking python version:' &&
       python --version &&
-      (python -c 'import sys; sys.exit(0 if sys.version_info>=(3,8) else 2)' ||
-       (echo '\033[1;31mError: Python 3.8+ is required\033[m' && false)) &&
-      echo '\n\033[1;32mInstalling required python modules:\033[m' &&
+      (python -c "import sys; sys.exit(0 if sys.version_info >= (3,8) else 2)" ||
+      (echo  'Error: Python 3.8+ is required' && exit 1)) &&
+      echo 'Installing required python modules:' &&
       python -m pip install -r "$MELOS_ROOT_PATH/doc/_sphinx/requirements.txt" &&
-      echo '\n\033[1;32mInstalling dartdoc_json:\033[m' &&
+      echo 'Installing dartdoc_json:' &&
       dart pub global activate dartdoc_json &&
-      echo '\n\033[1;32mDone.\033[m'
+      echo 'Done.'
     description: Prepares the environment for documentation development.
 
   doc-build:
